inputs:
  # Note that github.ref is formatted like refs/tag/v1.2.3
  tag:
    description: 'The tag name of the release'
    required: true
runs:
  using: "composite"
  steps:
    - name: Hello
      run: echo "${{ inputs.tag }}"
      shell: bash
